server:
  port: 8006
spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: 101.132.142.58
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

